" interestind stess
noremap   [a<LEADER>   1k
noremap   [s<LEADER>   2k
noremap   [d<LEADER>   3k
noremap   [f<LEADER>   4k
noremap   [g<LEADER>   5k
noremap   [h<LEADER>   6k
noremap   [j<LEADER>   7k
noremap   [k<LEADER>   8k
noremap   [l<LEADER>   9k
noremap  [a;<LEADER>  10k
noremap  [aa<LEADER>  11k
noremap  [as<LEADER>  12k
noremap  [ad<LEADER>  13k
noremap  [af<LEADER>  14k
noremap  [ag<LEADER>  15k
noremap  [ah<LEADER>  16k
noremap  [aj<LEADER>  17k
noremap  [ak<LEADER>  18k
noremap  [al<LEADER>  19k
noremap  [s;<LEADER>  20k
noremap  [sa<LEADER>  21k
noremap  [ss<LEADER>  22k
noremap  [sd<LEADER>  23k
noremap  [sf<LEADER>  24k
noremap  [sg<LEADER>  25k
noremap  [sh<LEADER>  26k
noremap  [sj<LEADER>  27k
noremap  [sk<LEADER>  28k
noremap  [sl<LEADER>  29k
noremap  [d;<LEADER>  30k
noremap  [da<LEADER>  31k
noremap  [ds<LEADER>  32k
noremap  [dd<LEADER>  33k
noremap  [df<LEADER>  34k
noremap  [dg<LEADER>  35k
noremap  [dh<LEADER>  36k
noremap  [dj<LEADER>  37k
noremap  [dk<LEADER>  38k
noremap  [dl<LEADER>  39k
noremap  [f;<LEADER>  40k
noremap  [fa<LEADER>  41k
noremap  [fs<LEADER>  42k
noremap  [fd<LEADER>  43k
noremap  [ff<LEADER>  44k
noremap  [fg<LEADER>  45k
noremap  [fh<LEADER>  46k
noremap  [fj<LEADER>  47k
noremap  [fk<LEADER>  48k
noremap  [fl<LEADER>  49k
noremap  [g;<LEADER>  50k
noremap  [ga<LEADER>  51k
noremap  [gs<LEADER>  52k
noremap  [gd<LEADER>  53k
noremap  [gf<LEADER>  54k
noremap  [gg<LEADER>  55k
noremap  [gh<LEADER>  56k
noremap  [gj<LEADER>  57k
noremap  [gk<LEADER>  58k
noremap  [gl<LEADER>  59k
noremap  [h;<LEADER>  60k
noremap  [ha<LEADER>  61k
noremap  [hs<LEADER>  62k
noremap  [hd<LEADER>  63k
noremap  [hf<LEADER>  64k
noremap  [hg<LEADER>  65k
noremap  [hh<LEADER>  66k
noremap  [hj<LEADER>  67k
noremap  [hk<LEADER>  68k
noremap  [hl<LEADER>  69k
noremap  [j;<LEADER>  70k
noremap  [ja<LEADER>  71k
noremap  [js<LEADER>  72k
noremap  [jd<LEADER>  73k
noremap  [jf<LEADER>  74k
noremap  [jg<LEADER>  75k
noremap  [jh<LEADER>  76k
noremap  [jj<LEADER>  77k
noremap  [jk<LEADER>  78k
noremap  [jl<LEADER>  79k
noremap  [k;<LEADER>  80k
noremap  [ka<LEADER>  81k
noremap  [ks<LEADER>  82k
noremap  [kd<LEADER>  83k
noremap  [kf<LEADER>  84k
noremap  [kg<LEADER>  85k
noremap  [kh<LEADER>  86k
noremap  [kj<LEADER>  87k
noremap  [kk<LEADER>  88k
noremap  [kl<LEADER>  89k
noremap  [l;<LEADER>  90k
noremap  [la<LEADER>  91k
noremap  [ls<LEADER>  92k
noremap  [ld<LEADER>  93k
noremap  [lf<LEADER>  94k
noremap  [lg<LEADER>  95k
noremap  [lh<LEADER>  96k
noremap  [lj<LEADER>  97k
noremap  [lk<LEADER>  98k
noremap  [ll<LEADER>  99k
noremap [a;;<LEADER> 100k
noremap [a;a<LEADER> 101k
noremap [a;s<LEADER> 102k
noremap [a;d<LEADER> 103k
noremap [a;f<LEADER> 104k
noremap [a;g<LEADER> 105k
noremap [a;h<LEADER> 106k
noremap [a;j<LEADER> 107k
noremap [a;k<LEADER> 108k
noremap [a;l<LEADER> 109k
noremap [aa;<LEADER> 110k
noremap [aaa<LEADER> 111k
noremap [aas<LEADER> 112k
noremap [aad<LEADER> 113k
noremap [aaf<LEADER> 114k
noremap [aag<LEADER> 115k
noremap [aah<LEADER> 116k
noremap [aaj<LEADER> 117k
noremap [aak<LEADER> 118k
noremap [aal<LEADER> 119k
noremap [as;<LEADER> 120k
noremap [asa<LEADER> 121k
noremap [ass<LEADER> 122k
noremap [asd<LEADER> 123k
noremap [asf<LEADER> 124k
noremap [asg<LEADER> 125k
noremap [ash<LEADER> 126k
noremap [asj<LEADER> 127k
noremap [ask<LEADER> 128k
noremap [asl<LEADER> 129k
noremap [ad;<LEADER> 130k
noremap [ada<LEADER> 131k
noremap [ads<LEADER> 132k
noremap [add<LEADER> 133k
noremap [adf<LEADER> 134k
noremap [adg<LEADER> 135k
noremap [adh<LEADER> 136k
noremap [adj<LEADER> 137k
noremap [adk<LEADER> 138k
noremap [adl<LEADER> 139k
noremap [af;<LEADER> 140k
noremap [afa<LEADER> 141k
noremap [afs<LEADER> 142k
noremap [afd<LEADER> 143k
noremap [aff<LEADER> 144k
noremap [afg<LEADER> 145k
noremap [afh<LEADER> 146k
noremap [afj<LEADER> 147k
noremap [afk<LEADER> 148k
noremap [afl<LEADER> 149k
noremap [ag;<LEADER> 150k
noremap [aga<LEADER> 151k
noremap [ags<LEADER> 152k
noremap [agd<LEADER> 153k
noremap [agf<LEADER> 154k
noremap [agg<LEADER> 155k
noremap [agh<LEADER> 156k
noremap [agj<LEADER> 157k
noremap [agk<LEADER> 158k
noremap [agl<LEADER> 159k
noremap [ah;<LEADER> 160k
noremap [aha<LEADER> 161k
noremap [ahs<LEADER> 162k
noremap [ahd<LEADER> 163k
noremap [ahf<LEADER> 164k
noremap [ahg<LEADER> 165k
noremap [ahh<LEADER> 166k
noremap [ahj<LEADER> 167k
noremap [ahk<LEADER> 168k
noremap [ahl<LEADER> 169k
noremap [aj;<LEADER> 170k
noremap [aja<LEADER> 171k
noremap [ajs<LEADER> 172k
noremap [ajd<LEADER> 173k
noremap [ajf<LEADER> 174k
noremap [ajg<LEADER> 175k
noremap [ajh<LEADER> 176k
noremap [ajj<LEADER> 177k
noremap [ajk<LEADER> 178k
noremap [ajl<LEADER> 179k
noremap [ak;<LEADER> 180k
noremap [aka<LEADER> 181k
noremap [aks<LEADER> 182k
noremap [akd<LEADER> 183k
noremap [akf<LEADER> 184k
noremap [akg<LEADER> 185k
noremap [akh<LEADER> 186k
noremap [akj<LEADER> 187k
noremap [akk<LEADER> 188k
noremap [akl<LEADER> 189k
noremap [al;<LEADER> 190k
noremap [ala<LEADER> 191k
noremap [als<LEADER> 192k
noremap [ald<LEADER> 193k
noremap [alf<LEADER> 194k
noremap [alg<LEADER> 195k
noremap [alh<LEADER> 196k
noremap [alj<LEADER> 197k
noremap [alk<LEADER> 198k
noremap [all<LEADER> 199k
            
noremap   'a<LEADER>   1j
noremap   's<LEADER>   2j
noremap   'd<LEADER>   3j
noremap   'f<LEADER>   4j
noremap   'g<LEADER>   5j
noremap   'h<LEADER>   6j
noremap   'j<LEADER>   7j
noremap   'k<LEADER>   8j
noremap   'l<LEADER>   9j
noremap  'a;<LEADER>  10j
noremap  'aa<LEADER>  11j
noremap  'as<LEADER>  12j
noremap  'ad<LEADER>  13j
noremap  'af<LEADER>  14j
noremap  'ag<LEADER>  15j
noremap  'ah<LEADER>  16j
noremap  'aj<LEADER>  17j
noremap  'ak<LEADER>  18j
noremap  'al<LEADER>  19j
noremap  's;<LEADER>  20j
noremap  'sa<LEADER>  21j
noremap  'ss<LEADER>  22j
noremap  'sd<LEADER>  23j
noremap  'sf<LEADER>  24j
noremap  'sg<LEADER>  25j
noremap  'sh<LEADER>  26j
noremap  'sj<LEADER>  27j
noremap  'sk<LEADER>  28j
noremap  'sl<LEADER>  29j
noremap  'd;<LEADER>  30j
noremap  'da<LEADER>  31j
noremap  'ds<LEADER>  32j
noremap  'dd<LEADER>  33j
noremap  'df<LEADER>  34j
noremap  'dg<LEADER>  35j
noremap  'dh<LEADER>  36j
noremap  'dj<LEADER>  37j
noremap  'dk<LEADER>  38j
noremap  'dl<LEADER>  39j
noremap  'f;<LEADER>  40j
noremap  'fa<LEADER>  41j
noremap  'fs<LEADER>  42j
noremap  'fd<LEADER>  43j
noremap  'ff<LEADER>  44j
noremap  'fg<LEADER>  45j
noremap  'fh<LEADER>  46j
noremap  'fj<LEADER>  47j
noremap  'fk<LEADER>  48j
noremap  'fl<LEADER>  49j
noremap  'g;<LEADER>  50j
noremap  'ga<LEADER>  51j
noremap  'gs<LEADER>  52j
noremap  'gd<LEADER>  53j
noremap  'gf<LEADER>  54j
noremap  'gg<LEADER>  55j
noremap  'gh<LEADER>  56j
noremap  'gj<LEADER>  57j
noremap  'gk<LEADER>  58j
noremap  'gl<LEADER>  59j
noremap  'h;<LEADER>  60j
noremap  'ha<LEADER>  61j
noremap  'hs<LEADER>  62j
noremap  'hd<LEADER>  63j
noremap  'hf<LEADER>  64j
noremap  'hg<LEADER>  65j
noremap  'hh<LEADER>  66j
noremap  'hj<LEADER>  67j
noremap  'hk<LEADER>  68j
noremap  'hl<LEADER>  69j
noremap  'j;<LEADER>  70j
noremap  'ja<LEADER>  71j
noremap  'js<LEADER>  72j
noremap  'jd<LEADER>  73j
noremap  'jf<LEADER>  74j
noremap  'jg<LEADER>  75j
noremap  'jh<LEADER>  76j
noremap  'jj<LEADER>  77j
noremap  'jk<LEADER>  78j
noremap  'jl<LEADER>  79j
noremap  'k;<LEADER>  80j
noremap  'ka<LEADER>  81j
noremap  'ks<LEADER>  82j
noremap  'kd<LEADER>  83j
noremap  'kf<LEADER>  84j
noremap  'kg<LEADER>  85j
noremap  'kh<LEADER>  86j
noremap  'kj<LEADER>  87j
noremap  'kk<LEADER>  88j
noremap  'kl<LEADER>  89j
noremap  'l;<LEADER>  90j
noremap  'la<LEADER>  91j
noremap  'ls<LEADER>  92j
noremap  'ld<LEADER>  93j
noremap  'lf<LEADER>  94j
noremap  'lg<LEADER>  95j
noremap  'lh<LEADER>  96j
noremap  'lj<LEADER>  97j
noremap  'lk<LEADER>  98j
noremap  'll<LEADER>  99j
noremap 'a;;<LEADER> 100j
noremap 'a;a<LEADER> 101j
noremap 'a;s<LEADER> 102j
noremap 'a;d<LEADER> 103j
noremap 'a;f<LEADER> 104j
noremap 'a;g<LEADER> 105j
noremap 'a;h<LEADER> 106j
noremap 'a;j<LEADER> 107j
noremap 'a;k<LEADER> 108j
noremap 'a;l<LEADER> 109j
noremap 'aa;<LEADER> 110j
noremap 'aaa<LEADER> 111j
noremap 'aas<LEADER> 112j
noremap 'aad<LEADER> 113j
noremap 'aaf<LEADER> 114j
noremap 'aag<LEADER> 115j
noremap 'aah<LEADER> 116j
noremap 'aaj<LEADER> 117j
noremap 'aak<LEADER> 118j
noremap 'aal<LEADER> 119j
noremap 'as;<LEADER> 120j
noremap 'asa<LEADER> 121j
noremap 'ass<LEADER> 122j
noremap 'asd<LEADER> 123j
noremap 'asf<LEADER> 124j
noremap 'asg<LEADER> 125j
noremap 'ash<LEADER> 126j
noremap 'asj<LEADER> 127j
noremap 'ask<LEADER> 128j
noremap 'asl<LEADER> 129j
noremap 'ad;<LEADER> 130j
noremap 'ada<LEADER> 131j
noremap 'ads<LEADER> 132j
noremap 'add<LEADER> 133j
noremap 'adf<LEADER> 134j
noremap 'adg<LEADER> 135j
noremap 'adh<LEADER> 136j
noremap 'adj<LEADER> 137j
noremap 'adk<LEADER> 138j
noremap 'adl<LEADER> 139j
noremap 'af;<LEADER> 140j
noremap 'afa<LEADER> 141j
noremap 'afs<LEADER> 142j
noremap 'afd<LEADER> 143j
noremap 'aff<LEADER> 144j
noremap 'afg<LEADER> 145j
noremap 'afh<LEADER> 146j
noremap 'afj<LEADER> 147j
noremap 'afk<LEADER> 148j
noremap 'afl<LEADER> 149j
noremap 'ag;<LEADER> 150j
noremap 'aga<LEADER> 151j
noremap 'ags<LEADER> 152j
noremap 'agd<LEADER> 153j
noremap 'agf<LEADER> 154j
noremap 'agg<LEADER> 155j
noremap 'agh<LEADER> 156j
noremap 'agj<LEADER> 157j
noremap 'agk<LEADER> 158j
noremap 'agl<LEADER> 159j
noremap 'ah;<LEADER> 160j
noremap 'aha<LEADER> 161j
noremap 'ahs<LEADER> 162j
noremap 'ahd<LEADER> 163j
noremap 'ahf<LEADER> 164j
noremap 'ahg<LEADER> 165j
noremap 'ahh<LEADER> 166j
noremap 'ahj<LEADER> 167j
noremap 'ahk<LEADER> 168j
noremap 'ahl<LEADER> 169j
noremap 'aj;<LEADER> 170j
noremap 'aja<LEADER> 171j
noremap 'ajs<LEADER> 172j
noremap 'ajd<LEADER> 173j
noremap 'ajf<LEADER> 174j
noremap 'ajg<LEADER> 175j
noremap 'ajh<LEADER> 176j
noremap 'ajj<LEADER> 177j
noremap 'ajk<LEADER> 178j
noremap 'ajl<LEADER> 179j
noremap 'ak;<LEADER> 180j
noremap 'aka<LEADER> 181j
noremap 'aks<LEADER> 182j
noremap 'akd<LEADER> 183j
noremap 'akf<LEADER> 184j
noremap 'akg<LEADER> 185j
noremap 'akh<LEADER> 186j
noremap 'akj<LEADER> 187j
noremap 'akk<LEADER> 188j
noremap 'akl<LEADER> 189j
noremap 'al;<LEADER> 190j
noremap 'ala<LEADER> 191j
noremap 'als<LEADER> 192j
noremap 'ald<LEADER> 193j
noremap 'alf<LEADER> 194j
noremap 'alg<LEADER> 195j
noremap 'alh<LEADER> 196j
noremap 'alj<LEADER> 197j
noremap 'alk<LEADER> 198j
noremap 'all<LEADER> 199j
