" interesting stuff
noremap   [q<LEADER>   1k
noremap   [w<LEADER>   2k
noremap   [f<LEADER>   3k
noremap   [p<LEADER>   4k
noremap   [g<LEADER>   5k
noremap   [j<LEADER>   6k
noremap   [l<LEADER>   7k
noremap   [u<LEADER>   8k
noremap   [y<LEADER>   9k
noremap  [q;<LEADER>  10k
noremap  [qq<LEADER>  11k
noremap  [qw<LEADER>  12k
noremap  [qf<LEADER>  13k
noremap  [qp<LEADER>  14k
noremap  [qg<LEADER>  15k
noremap  [qj<LEADER>  16k
noremap  [ql<LEADER>  17k
noremap  [qu<LEADER>  18k
noremap  [qy<LEADER>  19k
noremap  [w;<LEADER>  20k
noremap  [wq<LEADER>  21k
noremap  [ww<LEADER>  22k
noremap  [wf<LEADER>  23k
noremap  [wp<LEADER>  24k
noremap  [wg<LEADER>  25k
noremap  [wj<LEADER>  26k
noremap  [wl<LEADER>  27k
noremap  [wu<LEADER>  28k
noremap  [wy<LEADER>  29k
noremap  [f;<LEADER>  30k
noremap  [fq<LEADER>  31k
noremap  [fw<LEADER>  32k
noremap  [ff<LEADER>  33k
noremap  [fp<LEADER>  34k
noremap  [fg<LEADER>  35k
noremap  [fj<LEADER>  36k
noremap  [fl<LEADER>  37k
noremap  [fu<LEADER>  38k
noremap  [fy<LEADER>  39k
noremap  [p;<LEADER>  40k
noremap  [pq<LEADER>  41k
noremap  [pw<LEADER>  42k
noremap  [pf<LEADER>  43k
noremap  [pp<LEADER>  44k
noremap  [pg<LEADER>  45k
noremap  [pj<LEADER>  46k
noremap  [pl<LEADER>  47k
noremap  [pu<LEADER>  48k
noremap  [py<LEADER>  49k
noremap  [g;<LEADER>  50k
noremap  [gq<LEADER>  51k
noremap  [gw<LEADER>  52k
noremap  [gf<LEADER>  53k
noremap  [gp<LEADER>  54k
noremap  [gg<LEADER>  55k
noremap  [gj<LEADER>  56k
noremap  [gl<LEADER>  57k
noremap  [gu<LEADER>  58k
noremap  [gy<LEADER>  59k
noremap  [j;<LEADER>  60k
noremap  [jq<LEADER>  61k
noremap  [jw<LEADER>  62k
noremap  [jf<LEADER>  63k
noremap  [jp<LEADER>  64k
noremap  [jg<LEADER>  65k
noremap  [jj<LEADER>  66k
noremap  [jl<LEADER>  67k
noremap  [ju<LEADER>  68k
noremap  [jy<LEADER>  69k
noremap  [l;<LEADER>  70k
noremap  [lq<LEADER>  71k
noremap  [lw<LEADER>  72k
noremap  [lf<LEADER>  73k
noremap  [lp<LEADER>  74k
noremap  [lg<LEADER>  75k
noremap  [lj<LEADER>  76k
noremap  [ll<LEADER>  77k
noremap  [lu<LEADER>  78k
noremap  [ly<LEADER>  79k
noremap  [u;<LEADER>  80k
noremap  [uq<LEADER>  81k
noremap  [uw<LEADER>  82k
noremap  [uf<LEADER>  83k
noremap  [up<LEADER>  84k
noremap  [ug<LEADER>  85k
noremap  [uj<LEADER>  86k
noremap  [ul<LEADER>  87k
noremap  [uu<LEADER>  88k
noremap  [uy<LEADER>  89k
noremap  [y;<LEADER>  90k
noremap  [yq<LEADER>  91k
noremap  [yw<LEADER>  92k
noremap  [yf<LEADER>  93k
noremap  [yp<LEADER>  94k
noremap  [yg<LEADER>  95k
noremap  [yj<LEADER>  96k
noremap  [yl<LEADER>  97k
noremap  [yu<LEADER>  98k
noremap  [yy<LEADER>  99k
noremap [q;;<LEADER> 100k
noremap [q;q<LEADER> 101k
noremap [q;w<LEADER> 102k
noremap [q;f<LEADER> 103k
noremap [q;p<LEADER> 104k
noremap [q;g<LEADER> 105k
noremap [q;j<LEADER> 106k
noremap [q;l<LEADER> 107k
noremap [q;u<LEADER> 108k
noremap [q;y<LEADER> 109k
noremap [qq;<LEADER> 110k
noremap [qqq<LEADER> 111k
noremap [qqw<LEADER> 112k
noremap [qqf<LEADER> 113k
noremap [qqp<LEADER> 114k
noremap [qqg<LEADER> 115k
noremap [qqj<LEADER> 116k
noremap [qql<LEADER> 117k
noremap [qqu<LEADER> 118k
noremap [qqy<LEADER> 119k
noremap [qw;<LEADER> 120k
noremap [qwq<LEADER> 121k
noremap [qww<LEADER> 122k
noremap [qwf<LEADER> 123k
noremap [qwp<LEADER> 124k
noremap [qwg<LEADER> 125k
noremap [qwj<LEADER> 126k
noremap [qwl<LEADER> 127k
noremap [qwu<LEADER> 128k
noremap [qwy<LEADER> 129k
noremap [qf;<LEADER> 130k
noremap [qfq<LEADER> 131k
noremap [qfw<LEADER> 132k
noremap [qff<LEADER> 133k
noremap [qfp<LEADER> 134k
noremap [qfg<LEADER> 135k
noremap [qfj<LEADER> 136k
noremap [qfl<LEADER> 137k
noremap [qfu<LEADER> 138k
noremap [qfy<LEADER> 139k
noremap [qp;<LEADER> 140k
noremap [qpq<LEADER> 141k
noremap [qpw<LEADER> 142k
noremap [qpf<LEADER> 143k
noremap [qpp<LEADER> 144k
noremap [qpg<LEADER> 145k
noremap [qpj<LEADER> 146k
noremap [qpl<LEADER> 147k
noremap [qpu<LEADER> 148k
noremap [qpy<LEADER> 149k
noremap [qg;<LEADER> 150k
noremap [qgq<LEADER> 151k
noremap [qgw<LEADER> 152k
noremap [qgf<LEADER> 153k
noremap [qgp<LEADER> 154k
noremap [qgg<LEADER> 155k
noremap [qgj<LEADER> 156k
noremap [qgl<LEADER> 157k
noremap [qgu<LEADER> 158k
noremap [qgy<LEADER> 159k
noremap [qj;<LEADER> 160k
noremap [qjq<LEADER> 161k
noremap [qjw<LEADER> 162k
noremap [qjf<LEADER> 163k
noremap [qjp<LEADER> 164k
noremap [qjg<LEADER> 165k
noremap [qjj<LEADER> 166k
noremap [qjl<LEADER> 167k
noremap [qju<LEADER> 168k
noremap [qjy<LEADER> 169k
noremap [ql;<LEADER> 170k
noremap [qlq<LEADER> 171k
noremap [qlw<LEADER> 172k
noremap [qlf<LEADER> 173k
noremap [qlp<LEADER> 174k
noremap [qlg<LEADER> 175k
noremap [qlj<LEADER> 176k
noremap [qll<LEADER> 177k
noremap [qlu<LEADER> 178k
noremap [qly<LEADER> 179k
noremap [qu;<LEADER> 180k
noremap [quq<LEADER> 181k
noremap [quw<LEADER> 182k
noremap [quf<LEADER> 183k
noremap [qup<LEADER> 184k
noremap [qug<LEADER> 185k
noremap [quj<LEADER> 186k
noremap [qul<LEADER> 187k
noremap [quu<LEADER> 188k
noremap [quy<LEADER> 189k
noremap [qy;<LEADER> 190k
noremap [qyq<LEADER> 191k
noremap [qyw<LEADER> 192k
noremap [qyf<LEADER> 193k
noremap [qyp<LEADER> 194k
noremap [qyg<LEADER> 195k
noremap [qyj<LEADER> 196k
noremap [qyl<LEADER> 197k
noremap [qyu<LEADER> 198k
noremap [qyy<LEADER> 199k

noremap   'q<LEADER>   1j
noremap   'w<LEADER>   2j
noremap   'f<LEADER>   3j
noremap   'p<LEADER>   4j
noremap   'g<LEADER>   5j
noremap   'j<LEADER>   6j
noremap   'l<LEADER>   7j
noremap   'u<LEADER>   8j
noremap   'y<LEADER>   9j
noremap  'q;<LEADER>  10j
noremap  'qq<LEADER>  11j
noremap  'qw<LEADER>  12j
noremap  'qf<LEADER>  13j
noremap  'qp<LEADER>  14j
noremap  'qg<LEADER>  15j
noremap  'qj<LEADER>  16j
noremap  'ql<LEADER>  17j
noremap  'qu<LEADER>  18j
noremap  'qy<LEADER>  19j
noremap  'w;<LEADER>  20j
noremap  'wq<LEADER>  21j
noremap  'ww<LEADER>  22j
noremap  'wf<LEADER>  23j
noremap  'wp<LEADER>  24j
noremap  'wg<LEADER>  25j
noremap  'wj<LEADER>  26j
noremap  'wl<LEADER>  27j
noremap  'wu<LEADER>  28j
noremap  'wy<LEADER>  29j
noremap  'f;<LEADER>  30j
noremap  'fq<LEADER>  31j
noremap  'fw<LEADER>  32j
noremap  'ff<LEADER>  33j
noremap  'fp<LEADER>  34j
noremap  'fg<LEADER>  35j
noremap  'fj<LEADER>  36j
noremap  'fl<LEADER>  37j
noremap  'fu<LEADER>  38j
noremap  'fy<LEADER>  39j
noremap  'p;<LEADER>  40j
noremap  'pq<LEADER>  41j
noremap  'pw<LEADER>  42j
noremap  'pf<LEADER>  43j
noremap  'pp<LEADER>  44j
noremap  'pg<LEADER>  45j
noremap  'pj<LEADER>  46j
noremap  'pl<LEADER>  47j
noremap  'pu<LEADER>  48j
noremap  'py<LEADER>  49j
noremap  'g;<LEADER>  50j
noremap  'gq<LEADER>  51j
noremap  'gw<LEADER>  52j
noremap  'gf<LEADER>  53j
noremap  'gp<LEADER>  54j
noremap  'gg<LEADER>  55j
noremap  'gj<LEADER>  56j
noremap  'gl<LEADER>  57j
noremap  'gu<LEADER>  58j
noremap  'gy<LEADER>  59j
noremap  'j;<LEADER>  60j
noremap  'jq<LEADER>  61j
noremap  'jw<LEADER>  62j
noremap  'jf<LEADER>  63j
noremap  'jp<LEADER>  64j
noremap  'jg<LEADER>  65j
noremap  'jj<LEADER>  66j
noremap  'jl<LEADER>  67j
noremap  'ju<LEADER>  68j
noremap  'jy<LEADER>  69j
noremap  'l;<LEADER>  70j
noremap  'lq<LEADER>  71j
noremap  'lw<LEADER>  72j
noremap  'lf<LEADER>  73j
noremap  'lp<LEADER>  74j
noremap  'lg<LEADER>  75j
noremap  'lj<LEADER>  76j
noremap  'll<LEADER>  77j
noremap  'lu<LEADER>  78j
noremap  'ly<LEADER>  79j
noremap  'u;<LEADER>  80j
noremap  'uq<LEADER>  81j
noremap  'uw<LEADER>  82j
noremap  'uf<LEADER>  83j
noremap  'up<LEADER>  84j
noremap  'ug<LEADER>  85j
noremap  'uj<LEADER>  86j
noremap  'ul<LEADER>  87j
noremap  'uu<LEADER>  88j
noremap  'uy<LEADER>  89j
noremap  'y;<LEADER>  90j
noremap  'yq<LEADER>  91j
noremap  'yw<LEADER>  92j
noremap  'yf<LEADER>  93j
noremap  'yp<LEADER>  94j
noremap  'yg<LEADER>  95j
noremap  'yj<LEADER>  96j
noremap  'yl<LEADER>  97j
noremap  'yu<LEADER>  98j
noremap  'yy<LEADER>  99j
noremap 'q;;<LEADER> 100j
noremap 'q;q<LEADER> 101j
noremap 'q;w<LEADER> 102j
noremap 'q;f<LEADER> 103j
noremap 'q;p<LEADER> 104j
noremap 'q;g<LEADER> 105j
noremap 'q;j<LEADER> 106j
noremap 'q;l<LEADER> 107j
noremap 'q;u<LEADER> 108j
noremap 'q;y<LEADER> 109j
noremap 'qq;<LEADER> 110j
noremap 'qqq<LEADER> 111j
noremap 'qqw<LEADER> 112j
noremap 'qqf<LEADER> 113j
noremap 'qqp<LEADER> 114j
noremap 'qqg<LEADER> 115j
noremap 'qqj<LEADER> 116j
noremap 'qql<LEADER> 117j
noremap 'qqu<LEADER> 118j
noremap 'qqy<LEADER> 119j
noremap 'qw;<LEADER> 120j
noremap 'qwq<LEADER> 121j
noremap 'qww<LEADER> 122j
noremap 'qwf<LEADER> 123j
noremap 'qwp<LEADER> 124j
noremap 'qwg<LEADER> 125j
noremap 'qwj<LEADER> 126j
noremap 'qwl<LEADER> 127j
noremap 'qwu<LEADER> 128j
noremap 'qwy<LEADER> 129j
noremap 'qf;<LEADER> 130j
noremap 'qfq<LEADER> 131j
noremap 'qfw<LEADER> 132j
noremap 'qff<LEADER> 133j
noremap 'qfp<LEADER> 134j
noremap 'qfg<LEADER> 135j
noremap 'qfj<LEADER> 136j
noremap 'qfl<LEADER> 137j
noremap 'qfu<LEADER> 138j
noremap 'qfy<LEADER> 139j
noremap 'qp;<LEADER> 140j
noremap 'qpq<LEADER> 141j
noremap 'qpw<LEADER> 142j
noremap 'qpf<LEADER> 143j
noremap 'qpp<LEADER> 144j
noremap 'qpg<LEADER> 145j
noremap 'qpj<LEADER> 146j
noremap 'qpl<LEADER> 147j
noremap 'qpu<LEADER> 148j
noremap 'qpy<LEADER> 149j
noremap 'qg;<LEADER> 150j
noremap 'qgq<LEADER> 151j
noremap 'qgw<LEADER> 152j
noremap 'qgf<LEADER> 153j
noremap 'qgp<LEADER> 154j
noremap 'qgg<LEADER> 155j
noremap 'qgj<LEADER> 156j
noremap 'qgl<LEADER> 157j
noremap 'qgu<LEADER> 158j
noremap 'qgy<LEADER> 159j
noremap 'qj;<LEADER> 160j
noremap 'qjq<LEADER> 161j
noremap 'qjw<LEADER> 162j
noremap 'qjf<LEADER> 163j
noremap 'qjp<LEADER> 164j
noremap 'qjg<LEADER> 165j
noremap 'qjj<LEADER> 166j
noremap 'qjl<LEADER> 167j
noremap 'qju<LEADER> 168j
noremap 'qjy<LEADER> 169j
noremap 'ql;<LEADER> 170j
noremap 'qlq<LEADER> 171j
noremap 'qlw<LEADER> 172j
noremap 'qlf<LEADER> 173j
noremap 'qlp<LEADER> 174j
noremap 'qlg<LEADER> 175j
noremap 'qlj<LEADER> 176j
noremap 'qll<LEADER> 177j
noremap 'qlu<LEADER> 178j
noremap 'qly<LEADER> 179j
noremap 'qu;<LEADER> 180j
noremap 'quq<LEADER> 181j
noremap 'quw<LEADER> 182j
noremap 'quf<LEADER> 183j
noremap 'qup<LEADER> 184j
noremap 'qug<LEADER> 185j
noremap 'quj<LEADER> 186j
noremap 'qul<LEADER> 187j
noremap 'quu<LEADER> 188j
noremap 'quy<LEADER> 189j
noremap 'qy;<LEADER> 190j
noremap 'qyq<LEADER> 191j
noremap 'qyw<LEADER> 192j
noremap 'qyf<LEADER> 193j
noremap 'qyp<LEADER> 194j
noremap 'qyg<LEADER> 195j
noremap 'qyj<LEADER> 196j
noremap 'qyl<LEADER> 197j
noremap 'qyu<LEADER> 198j
noremap 'qyy<LEADER> 199j
