" interestind stess
noremap   [a<LEADER>   1k
noremap   [r<LEADER>   2k
noremap   [s<LEADER>   3k
noremap   [t<LEADER>   4k
noremap   [d<LEADER>   5k
noremap   [h<LEADER>   6k
noremap   [n<LEADER>   7k
noremap   [e<LEADER>   8k
noremap   [i<LEADER>   9k
noremap  [ao<LEADER>  10k
noremap  [aa<LEADER>  11k
noremap  [ar<LEADER>  12k
noremap  [as<LEADER>  13k
noremap  [at<LEADER>  14k
noremap  [ad<LEADER>  15k
noremap  [ah<LEADER>  16k
noremap  [an<LEADER>  17k
noremap  [ae<LEADER>  18k
noremap  [ai<LEADER>  19k
noremap  [ro<LEADER>  20k
noremap  [ra<LEADER>  21k
noremap  [rr<LEADER>  22k
noremap  [rs<LEADER>  23k
noremap  [rt<LEADER>  24k
noremap  [rd<LEADER>  25k
noremap  [rh<LEADER>  26k
noremap  [rn<LEADER>  27k
noremap  [re<LEADER>  28k
noremap  [ri<LEADER>  29k
noremap  [so<LEADER>  30k
noremap  [sa<LEADER>  31k
noremap  [sr<LEADER>  32k
noremap  [ss<LEADER>  33k
noremap  [st<LEADER>  34k
noremap  [sd<LEADER>  35k
noremap  [sh<LEADER>  36k
noremap  [sn<LEADER>  37k
noremap  [se<LEADER>  38k
noremap  [si<LEADER>  39k
noremap  [to<LEADER>  40k
noremap  [ta<LEADER>  41k
noremap  [tr<LEADER>  42k
noremap  [ts<LEADER>  43k
noremap  [tt<LEADER>  44k
noremap  [td<LEADER>  45k
noremap  [th<LEADER>  46k
noremap  [tn<LEADER>  47k
noremap  [te<LEADER>  48k
noremap  [ti<LEADER>  49k
noremap  [do<LEADER>  50k
noremap  [da<LEADER>  51k
noremap  [dr<LEADER>  52k
noremap  [ds<LEADER>  53k
noremap  [dt<LEADER>  54k
noremap  [dd<LEADER>  55k
noremap  [dh<LEADER>  56k
noremap  [dn<LEADER>  57k
noremap  [de<LEADER>  58k
noremap  [di<LEADER>  59k
noremap  [ho<LEADER>  60k
noremap  [ha<LEADER>  61k
noremap  [hr<LEADER>  62k
noremap  [hs<LEADER>  63k
noremap  [ht<LEADER>  64k
noremap  [hd<LEADER>  65k
noremap  [hh<LEADER>  66k
noremap  [hn<LEADER>  67k
noremap  [he<LEADER>  68k
noremap  [hi<LEADER>  69k
noremap  [no<LEADER>  70k
noremap  [na<LEADER>  71k
noremap  [nr<LEADER>  72k
noremap  [ns<LEADER>  73k
noremap  [nt<LEADER>  74k
noremap  [nd<LEADER>  75k
noremap  [nh<LEADER>  76k
noremap  [nn<LEADER>  77k
noremap  [ne<LEADER>  78k
noremap  [ni<LEADER>  79k
noremap  [eo<LEADER>  80k
noremap  [ea<LEADER>  81k
noremap  [er<LEADER>  82k
noremap  [es<LEADER>  83k
noremap  [et<LEADER>  84k
noremap  [ed<LEADER>  85k
noremap  [eh<LEADER>  86k
noremap  [en<LEADER>  87k
noremap  [ee<LEADER>  88k
noremap  [ei<LEADER>  89k
noremap  [io<LEADER>  90k
noremap  [ia<LEADER>  91k
noremap  [ir<LEADER>  92k
noremap  [is<LEADER>  93k
noremap  [it<LEADER>  94k
noremap  [id<LEADER>  95k
noremap  [ih<LEADER>  96k
noremap  [in<LEADER>  97k
noremap  [ie<LEADER>  98k
noremap  [ii<LEADER>  99k
noremap [aoo<LEADER> 100k
noremap [aoa<LEADER> 101k
noremap [aor<LEADER> 102k
noremap [aos<LEADER> 103k
noremap [aot<LEADER> 104k
noremap [aod<LEADER> 105k
noremap [aoh<LEADER> 106k
noremap [aon<LEADER> 107k
noremap [aoe<LEADER> 108k
noremap [aoi<LEADER> 109k
noremap [aao<LEADER> 110k
noremap [aaa<LEADER> 111k
noremap [aar<LEADER> 112k
noremap [aas<LEADER> 113k
noremap [aat<LEADER> 114k
noremap [aad<LEADER> 115k
noremap [aah<LEADER> 116k
noremap [aan<LEADER> 117k
noremap [aae<LEADER> 118k
noremap [aai<LEADER> 119k
noremap [aro<LEADER> 120k
noremap [ara<LEADER> 121k
noremap [arr<LEADER> 122k
noremap [ars<LEADER> 123k
noremap [art<LEADER> 124k
noremap [ard<LEADER> 125k
noremap [arh<LEADER> 126k
noremap [arn<LEADER> 127k
noremap [are<LEADER> 128k
noremap [ari<LEADER> 129k
noremap [aso<LEADER> 130k
noremap [asa<LEADER> 131k
noremap [asr<LEADER> 132k
noremap [ass<LEADER> 133k
noremap [ast<LEADER> 134k
noremap [asd<LEADER> 135k
noremap [ash<LEADER> 136k
noremap [asn<LEADER> 137k
noremap [ase<LEADER> 138k
noremap [asi<LEADER> 139k
noremap [ato<LEADER> 140k
noremap [ata<LEADER> 141k
noremap [atr<LEADER> 142k
noremap [ats<LEADER> 143k
noremap [att<LEADER> 144k
noremap [atd<LEADER> 145k
noremap [ath<LEADER> 146k
noremap [atn<LEADER> 147k
noremap [ate<LEADER> 148k
noremap [ati<LEADER> 149k
noremap [ado<LEADER> 150k
noremap [ada<LEADER> 151k
noremap [adr<LEADER> 152k
noremap [ads<LEADER> 153k
noremap [adt<LEADER> 154k
noremap [add<LEADER> 155k
noremap [adh<LEADER> 156k
noremap [adn<LEADER> 157k
noremap [ade<LEADER> 158k
noremap [adi<LEADER> 159k
noremap [aho<LEADER> 160k
noremap [aha<LEADER> 161k
noremap [ahr<LEADER> 162k
noremap [ahs<LEADER> 163k
noremap [aht<LEADER> 164k
noremap [ahd<LEADER> 165k
noremap [ahh<LEADER> 166k
noremap [ahn<LEADER> 167k
noremap [ahe<LEADER> 168k
noremap [ahi<LEADER> 169k
noremap [ano<LEADER> 170k
noremap [ana<LEADER> 171k
noremap [anr<LEADER> 172k
noremap [ans<LEADER> 173k
noremap [ant<LEADER> 174k
noremap [and<LEADER> 175k
noremap [anh<LEADER> 176k
noremap [ann<LEADER> 177k
noremap [ane<LEADER> 178k
noremap [ani<LEADER> 179k
noremap [aeo<LEADER> 180k
noremap [aea<LEADER> 181k
noremap [aer<LEADER> 182k
noremap [aes<LEADER> 183k
noremap [aet<LEADER> 184k
noremap [aed<LEADER> 185k
noremap [aeh<LEADER> 186k
noremap [aen<LEADER> 187k
noremap [aee<LEADER> 188k
noremap [aei<LEADER> 189k
noremap [aio<LEADER> 190k
noremap [aia<LEADER> 191k
noremap [air<LEADER> 192k
noremap [ais<LEADER> 193k
noremap [ait<LEADER> 194k
noremap [aid<LEADER> 195k
noremap [aih<LEADER> 196k
noremap [ain<LEADER> 197k
noremap [aie<LEADER> 198k
noremap [aii<LEADER> 199k

noremap   'a<LEADER>   1j
noremap   'r<LEADER>   2j
noremap   's<LEADER>   3j
noremap   't<LEADER>   4j
noremap   'd<LEADER>   5j
noremap   'h<LEADER>   6j
noremap   'n<LEADER>   7j
noremap   'e<LEADER>   8j
noremap   'i<LEADER>   9j
noremap  'ao<LEADER>  10j
noremap  'aa<LEADER>  11j
noremap  'ar<LEADER>  12j
noremap  'as<LEADER>  13j
noremap  'at<LEADER>  14j
noremap  'ad<LEADER>  15j
noremap  'ah<LEADER>  16j
noremap  'an<LEADER>  17j
noremap  'ae<LEADER>  18j
noremap  'ai<LEADER>  19j
noremap  'ro<LEADER>  20j
noremap  'ra<LEADER>  21j
noremap  'rr<LEADER>  22j
noremap  'rs<LEADER>  23j
noremap  'rt<LEADER>  24j
noremap  'rd<LEADER>  25j
noremap  'rh<LEADER>  26j
noremap  'rn<LEADER>  27j
noremap  're<LEADER>  28j
noremap  'ri<LEADER>  29j
noremap  'so<LEADER>  30j
noremap  'sa<LEADER>  31j
noremap  'sr<LEADER>  32j
noremap  'ss<LEADER>  33j
noremap  'st<LEADER>  34j
noremap  'sd<LEADER>  35j
noremap  'sh<LEADER>  36j
noremap  'sn<LEADER>  37j
noremap  'se<LEADER>  38j
noremap  'si<LEADER>  39j
noremap  'to<LEADER>  40j
noremap  'ta<LEADER>  41j
noremap  'tr<LEADER>  42j
noremap  'ts<LEADER>  43j
noremap  'tt<LEADER>  44j
noremap  'td<LEADER>  45j
noremap  'th<LEADER>  46j
noremap  'tn<LEADER>  47j
noremap  'te<LEADER>  48j
noremap  'ti<LEADER>  49j
noremap  'do<LEADER>  50j
noremap  'da<LEADER>  51j
noremap  'dr<LEADER>  52j
noremap  'ds<LEADER>  53j
noremap  'dt<LEADER>  54j
noremap  'dd<LEADER>  55j
noremap  'dh<LEADER>  56j
noremap  'dn<LEADER>  57j
noremap  'de<LEADER>  58j
noremap  'di<LEADER>  59j
noremap  'ho<LEADER>  60j
noremap  'ha<LEADER>  61j
noremap  'hr<LEADER>  62j
noremap  'hs<LEADER>  63j
noremap  'ht<LEADER>  64j
noremap  'hd<LEADER>  65j
noremap  'hh<LEADER>  66j
noremap  'hn<LEADER>  67j
noremap  'he<LEADER>  68j
noremap  'hi<LEADER>  69j
noremap  'no<LEADER>  70j
noremap  'na<LEADER>  71j
noremap  'nr<LEADER>  72j
noremap  'ns<LEADER>  73j
noremap  'nt<LEADER>  74j
noremap  'nd<LEADER>  75j
noremap  'nh<LEADER>  76j
noremap  'nn<LEADER>  77j
noremap  'ne<LEADER>  78j
noremap  'ni<LEADER>  79j
noremap  'eo<LEADER>  80j
noremap  'ea<LEADER>  81j
noremap  'er<LEADER>  82j
noremap  'es<LEADER>  83j
noremap  'et<LEADER>  84j
noremap  'ed<LEADER>  85j
noremap  'eh<LEADER>  86j
noremap  'en<LEADER>  87j
noremap  'ee<LEADER>  88j
noremap  'ei<LEADER>  89j
noremap  'io<LEADER>  90j
noremap  'ia<LEADER>  91j
noremap  'ir<LEADER>  92j
noremap  'is<LEADER>  93j
noremap  'it<LEADER>  94j
noremap  'id<LEADER>  95j
noremap  'ih<LEADER>  96j
noremap  'in<LEADER>  97j
noremap  'ie<LEADER>  98j
noremap  'ii<LEADER>  99j
noremap 'aoo<LEADER> 100j
noremap 'aoa<LEADER> 101j
noremap 'aor<LEADER> 102j
noremap 'aos<LEADER> 103j
noremap 'aot<LEADER> 104j
noremap 'aod<LEADER> 105j
noremap 'aoh<LEADER> 106j
noremap 'aon<LEADER> 107j
noremap 'aoe<LEADER> 108j
noremap 'aoi<LEADER> 109j
noremap 'aao<LEADER> 110j
noremap 'aaa<LEADER> 111j
noremap 'aar<LEADER> 112j
noremap 'aas<LEADER> 113j
noremap 'aat<LEADER> 114j
noremap 'aad<LEADER> 115j
noremap 'aah<LEADER> 116j
noremap 'aan<LEADER> 117j
noremap 'aae<LEADER> 118j
noremap 'aai<LEADER> 119j
noremap 'aro<LEADER> 120j
noremap 'ara<LEADER> 121j
noremap 'arr<LEADER> 122j
noremap 'ars<LEADER> 123j
noremap 'art<LEADER> 124j
noremap 'ard<LEADER> 125j
noremap 'arh<LEADER> 126j
noremap 'arn<LEADER> 127j
noremap 'are<LEADER> 128j
noremap 'ari<LEADER> 129j
noremap 'aso<LEADER> 130j
noremap 'asa<LEADER> 131j
noremap 'asr<LEADER> 132j
noremap 'ass<LEADER> 133j
noremap 'ast<LEADER> 134j
noremap 'asd<LEADER> 135j
noremap 'ash<LEADER> 136j
noremap 'asn<LEADER> 137j
noremap 'ase<LEADER> 138j
noremap 'asi<LEADER> 139j
noremap 'ato<LEADER> 140j
noremap 'ata<LEADER> 141j
noremap 'atr<LEADER> 142j
noremap 'ats<LEADER> 143j
noremap 'att<LEADER> 144j
noremap 'atd<LEADER> 145j
noremap 'ath<LEADER> 146j
noremap 'atn<LEADER> 147j
noremap 'ate<LEADER> 148j
noremap 'ati<LEADER> 149j
noremap 'ado<LEADER> 150j
noremap 'ada<LEADER> 151j
noremap 'adr<LEADER> 152j
noremap 'ads<LEADER> 153j
noremap 'adt<LEADER> 154j
noremap 'add<LEADER> 155j
noremap 'adh<LEADER> 156j
noremap 'adn<LEADER> 157j
noremap 'ade<LEADER> 158j
noremap 'adi<LEADER> 159j
noremap 'aho<LEADER> 160j
noremap 'aha<LEADER> 161j
noremap 'ahr<LEADER> 162j
noremap 'ahs<LEADER> 163j
noremap 'aht<LEADER> 164j
noremap 'ahd<LEADER> 165j
noremap 'ahh<LEADER> 166j
noremap 'ahn<LEADER> 167j
noremap 'ahe<LEADER> 168j
noremap 'ahi<LEADER> 169j
noremap 'ano<LEADER> 170j
noremap 'ana<LEADER> 171j
noremap 'anr<LEADER> 172j
noremap 'ans<LEADER> 173j
noremap 'ant<LEADER> 174j
noremap 'and<LEADER> 175j
noremap 'anh<LEADER> 176j
noremap 'ann<LEADER> 177j
noremap 'ane<LEADER> 178j
noremap 'ani<LEADER> 179j
noremap 'aeo<LEADER> 180j
noremap 'aea<LEADER> 181j
noremap 'aer<LEADER> 182j
noremap 'aes<LEADER> 183j
noremap 'aet<LEADER> 184j
noremap 'aed<LEADER> 185j
noremap 'aeh<LEADER> 186j
noremap 'aen<LEADER> 187j
noremap 'aee<LEADER> 188j
noremap 'aei<LEADER> 189j
noremap 'aio<LEADER> 190j
noremap 'aia<LEADER> 191j
noremap 'air<LEADER> 192j
noremap 'ais<LEADER> 193j
noremap 'ait<LEADER> 194j
noremap 'aid<LEADER> 195j
noremap 'aih<LEADER> 196j
noremap 'ain<LEADER> 197j
noremap 'aie<LEADER> 198j
noremap 'aii<LEADER> 199j
